### ISSUE TITLE
[metalsmith-html-relative] Imports non-existent import from `cheerio`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [emmercm/metalsmith-plugins#150]
`metalsmith-html-relative` contains this import at [line 1 of `index.js`](https://yarnpkg.com/package?name=metalsmith-html-relative&file=%2Fdist%2Findex.js):
```js
import cheerio from "cheerio"
```

However, `cheerio` has no default export: https://yarnpkg.com/package?name=cheerio&file=%2Fdist%2Fesm%2Findex.js

For this reason, trying to use `metalsmith-html-relative` throws the following error:
```
import cheerio from 'cheerio';
       ^^^^^^^
SyntaxError: The requested module 'cheerio' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:171:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:254:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:482:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)

Node.js v22.8.0

```

**Comment by emmercm** [comment]
I suppose this is what happens when the project chooses to use release candidate naming for 4 years... thank you for reporting, I hadn't seen it was finally released. I'll work on accepting your PRs this week.
